apiVersion: v1
kind: Secret
metadata:
    name: airflow-admin
    namespace: airflow
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:dYaY3xU=,iv:LmdaoWvZAz9y3iJK7IPnLMcoVF3dH3u9TJSP9pKsWx0=,tag:f9epjqQBHzFdHQUObColJg==,type:str]
    password: ENC[AES256_GCM,data:f3plEDp4lX8AvouDUyU9XiK+OvGt0kA5TstwI/fFjpg=,iv:8TNqsArsJZk69AS22Vb7bH2hdAxAeJ2/9ZbbJFFkXYw=,tag:wKZQBxGjfsLSMbPaUA2Ltw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4TGJHblcvTEUxT245cFV0
            dW51M25TeGZxektlVFhEYWpXcUQvbjdaNVR3CkNuOXE5OEVLZ2pxZ1lUWnhsbUo5
            K2k0TEFRYy9YcGlCZWJWMjVnOVJUT2cKLS0tIEwxdHI3L29Lc2FDNnUzZlNJeloy
            RmlLcktIelR4eHJ4U0FWTFNTUHY2NkkKQPbfd3CC8Ije6Xm/qnJWdW1KawhQtPIu
            5P/WiuAs+IVgjCkXUEye25CaEckK4ZeonW9QjWrwHhvZI9uDm1258Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:57:10Z"
    mac: ENC[AES256_GCM,data:anAhuJU3XyTPaCZ4yI8+YLPgbYpf4jfBwItTPiYovwJWw9j/bA+WROYgD+wFQHWOLQKlefYba6oYtYaHkO7dlNwqelItIy1kDpe1pMIO5m9K9yNqUe6tiQjhxDSarREzYini8Ihc3JWjezcEUbdkS6GnNsOvX/MQ8aoC0vavMrc=,iv:igZMVSTmBkHX693zgIEiEQlhQJdJSYTTgfSqtxJWjVc=,tag:J5vH5z2R2MwafZQK4DV+Pg==,type:str]
    version: 3.13.3
