apiVersion: v1
kind: Secret
metadata:
    name: airflow-keys
    namespace: airflow
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    fernet-key: ENC[AES256_GCM,data:judg1fPn/mFrVAk8++jzuJNGrtkfp6KSMZTCBeWhu5EvPscjAtpIE7HJGsI=,iv:VKAz0os93CntXmW45heuUdnnBtR5Dop4fnayVW0w8qo=,tag:ANvAOxeb5jBBtzrlQewNyg==,type:str]
    api-secret-key: ENC[AES256_GCM,data:nPVswdobAe7gsX8BKcQees7kLRVsHtzLfvI5erH1TzX4aehtth0pj6uuElu/UgXK3ncTfAkW3DgSzp/bhSN9og==,iv:VvYKX4RSOpGeqPp3EUKjqhGSRtThHCWqAeoNa3MTQrA=,tag:sOixrXCPC6T9ByLMZwPnPA==,type:str]
    jwt-secret: ENC[AES256_GCM,data:21ozxU9g/+Fw1R7FCgvr+CK0ISn0yroHqtyKb4uXnr9Cu4cB8c55xr1VD76IfhP+Fet36lJL0or/BTEaRcR7ag==,iv:3PPaAXckSHhuRpd08zbHH6huh0KKJ/wQpcIZ9uCA6QQ=,tag:sOc0SwVafCgexNuFi5uzRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dnYyMW9RK2RaL3lESkxx
            SEJOTmZMVDYxTFBOQzVmNWZ0MmdTTG1DR3hJClNjUjUxcVcrdDlwb0V1MWdVeU9o
            VU9ETHJJMHFqL1d5Z096VlRiWXlMMTAKLS0tIGZiUXRvdDFSdStvaWNtZHFNUkY3
            Y0xIWmg1eGdTZlBmZm9FVWt1VXRpWHcK1IGuIdj3g/V6JuUNTt3SJIOT6U3tE7EK
            f2kGqxOZ5hBTGqj0jE5gy6YUmzOyLeztewOietz88v2zsSOhLRmaHw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:57:10Z"
    mac: ENC[AES256_GCM,data:Bf72R0wzbdJBbCOUh+E7K4Or9q4LFpZzF56grRB65UIZM2RbpmMdU5tdF83YLlKWbCXdVZJKp1d4khiaWXOgV3NjAddqmgIOD0NfdAoNcmL/FiGIEqNRiWNhotGvt2RRdKKNLq0NkTvaodMPKu+Dfgtp1h+Xm0PR1uN0KFdrQVU=,iv:UQP4NLSkGM2phpUcEIqoT1MdZwRhZI1X5Z/ylIF14LY=,tag:YanqEODADZ+Rg/9ceEzmuA==,type:str]
    version: 3.13.3
