apiVersion: v1
kind: Secret
metadata:
    name: argocd-admin
    namespace: argocd
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:+34o3LYb/h/W51+1wiHDm+unagfVit/RqB13J8FhFFE=,iv:6HxMkexGY6sRf1Q7Y0YtE/HjYVRkOe62S2uUOBiTSFg=,tag:TxKGZ4OSQW9B5TEs8pRarQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZHoyTTJUWnJubDh1eGlX
            a3FBSmxVQlhnSUVpVFl3Y09nOGhxVVdFNWh3CnBtaEJac0FQbkFXUjJOVTNwUnc0
            QVg0K1ZhTjFORGs4Q3VmQXdHbERqeXMKLS0tIGhEa0IrK29Md2t0YWFTU3RzaTZQ
            ZUlocW40RzE0azJvRzZLY0NrYTJlQlEKVIKPr2iT2UdJRHcI3KyuHEHBuyiEL10w
            ahtMnIi1VLxDmeTz1W7xR1s0OeyJC7odD5cJ2FUYagqHIuz8/mpPEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T10:46:38Z"
    mac: ENC[AES256_GCM,data:8/qvJXQ1NiUeEXZlE8UQeZ7jXnMJK/fm5SmK95DrrCglQScU8LkI1Pemge3M2ENvcea+oY6rGSnKYESUaVdFEef+kDHhrvzSdz2Hd0Aj4y6MCBea2DPWWpzQU+xE3ibwWieUm4hPY5tV/hoqkLRF3hivKXXnR3dPrJX9QNVw3HI=,iv:f/zCqLfbIpsQaiQoJLC+Zsr8juf4Cxq/d6tEYZR1o/Q=,tag:4HMGBtB2RJgufHhC8vS8DA==,type:str]
    version: 3.13.3
