# KSOPS exec generator: decrypts the listed SOPS files into Secrets at build time.
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cluster-secrets
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./argocd-admin.enc.yaml
