#!/usr/bin/env bash
# Shop-like schema for the smoke test: a subset of the Alembic schema plus the CDC source objects of
# docs/contracts/services.md (heartbeat row, publication shop_cdc, REPLICATION role debezium with its grants).
set -euo pipefail

psql -v ON_ERROR_STOP=1 -U postgres -d shop -v debezium_password="$DEBEZIUM_PASSWORD" <<'SQL'
CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email text NOT NULL UNIQUE,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES customers (id),
    status text NOT NULL,
    total numeric(12, 2) NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE heartbeat (
    id smallint PRIMARY KEY CHECK (id = 1),
    beat_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO heartbeat (id) VALUES (1);

-- Rows that exist before the connector starts: they must arrive through the initial snapshot (_op = 'r').
INSERT INTO customers (email, name) VALUES ('a@example.test', 'Alice'), ('b@example.test', 'Bob');
INSERT INTO orders (customer_id, status, total) VALUES (1, 'paid', 12.50);

CREATE PUBLICATION shop_cdc FOR TABLE public.customers, public.orders, public.heartbeat;

CREATE ROLE debezium WITH LOGIN REPLICATION PASSWORD :'debezium_password';
GRANT USAGE ON SCHEMA public TO debezium;
GRANT SELECT ON public.customers, public.orders, public.heartbeat TO debezium;
GRANT UPDATE ON public.heartbeat TO debezium;
SQL
