apiVersion: v1
kind: Secret
metadata:
    name: shop-db-flink-serving
    namespace: shop
    labels:
        app.kubernetes.io/part-of: shopflow
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0iCuSjr7CkxEilXr5w==,iv:WdjxHncOT+oFhXsCuHMFlwdgd12WDnAf6j4K8oHTx9s=,tag:TKORrd2YSuLCZf0w+oXrbg==,type:str]
    password: ENC[AES256_GCM,data:hGNNzUxw8Dw6NN+4UGv6RQjQUv/+qIGv1/IGC7mhMRE=,iv:EepaLDAhQ6SOOrjCBzT7BMr1xcLfiDk4xufX0WPurY8=,tag:ZVDN8Bebvipa0EyaD6YyJw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSkNZZVNrcVNCN2lJYlh2
            dk9YTUMzdktuOWlHendsd1dxZTZXcUZZM2hzCmg5U3plamxXTytXRzZFRzJPODVP
            R25RQW5tK1F0OGNFNU5aQjlVVEllbFEKLS0tIDlWQ0VScFNHYU1zL3JRMG45RkVM
            QzU1VDZPOVR0UUovTFNkS1A1UVJDRUEKfIBH8jQyKQVmvp/9Cd1x0BK8Nta67tyC
            AQ2Z9ePW9y3w6QY2Y4V5UZfT5uhLYHOpASwTy8Sx8nPa+VUJ7hW0fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:06:44Z"
    mac: ENC[AES256_GCM,data:luTuHNYov/3IwyxxXwcqNixhKIYXLYlanNZAjUtHqwFJWRtNgFw6JIjlkYLbKHYl3MS8QdbucdkCPneu3Z2LvffSh3Q70Fla+S3um5GCqXd4Yqkv/UnfQ51BoAcniLRPTe1vZuDq8AxSXdTrjdzgY1HREQrKvciJPp70wt4kRtQ=,iv:ivvBHnEgYCMRxAWHI12l6eY1RxQN4EhBFga5DcFyGyI=,tag:xf0SCYVH/Hrn0pz/OtS2gg==,type:str]
    version: 3.13.3
