apiVersion: v1
kind: Secret
metadata:
    name: shop-db-trino-pg
    namespace: shop
    labels:
        app.kubernetes.io/part-of: shopflow
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:C7vEhliQZvw=,iv:9dTXzgbjRZrYUEem9zcvCL8dMI5DAgmSddIoS5y5R+k=,tag:R+nV5MVlsVZntGIQx4Ay3g==,type:str]
    password: ENC[AES256_GCM,data:cufGb9bhm+V9FWvoB0SHdCIzq7hE2UjG99NVmPdWthg=,iv:omJ/rizE4DIeidtgE42YzrGHYrCCNaulpmXovM/kIyw=,tag:ZTha1cYDYw7DWJsec/WTWA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNlBNNkxtRk1QSHpEY0lN
            ZWlRbm9LZEVKOTVHcldYSlVnQ2FveTQzUmdBCkN1Vnh2NlEzQkZ6MlFFbmVRelNV
            dEpmbndaS0JuMGNYbUJ1V0pDVVNzZkkKLS0tIG10dXowNERoNEFUQ0poWFhMa2d1
            VHg1TkxBajBDSFlrd1JpZ1lXMjVwL2MKTZh4kSmQLUbgvwtuw3bHCJFEGgik+AYL
            9WTI/pIQkQncHKqs2PFS8ohOQNau5YpO74EDkwU8DgA4Jqm4SJaS4g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:01:51Z"
    mac: ENC[AES256_GCM,data:VCSOh5vsoNA5ow/4aVCzROA4VV80JQUQTKjBlsCrRVPFV6o+IR0Nv5wkaxGqk69npUs2aK/c1leNRpGyNVDqhHaVl0ciDn6Zd5AaDvYgy9G8jC6bDlBkz2SOpg87hNzvsByN7TDoMKrznbtkgVCo90/UNdmmzfGJXLaq5IRM17M=,iv:rVX5lBr5fDzd3+CQLIDWNf+A/+I6xweQ8zxDsDwO6A8=,tag:Rg7aKlDJBajTh9PkZBAyew==,type:str]
    version: 3.13.3
