apiVersion: v1
kind: Secret
metadata:
    name: shop-db-airflow
    namespace: shop
    labels:
        app.kubernetes.io/part-of: shopflow
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:/9fCVvLGNA==,iv:vNwuFWlZVOGprBGgRUR+1hfZvtHM8laGImfdT2RHiaQ=,tag:lkCy3yd7SlMAcB8J6fzZMg==,type:str]
    password: ENC[AES256_GCM,data:9IJeyfM6EBMAZqVMfSSI9B/Z0Hg88G2L6XNyCicZYIA=,iv:UBsfzlfgoaCdJ2jlwnIFJd0CpQTPnP/6zoxUnKMEED4=,tag:vnRCq8F4l1E12CMzMZFwcQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoQ3owVzNVVmdHaWVuWkMr
            K0ErUkpGaVAxUXRubGNOUk56L1BTcDZsYVg0CmROSGZNRXBMeEhHeG14MWJXaTF1
            b0R1RkZDYUJ4NUtQa1lteXdHUnFqUlkKLS0tIEpkZlM0SnliZHRiVGtxK1NINHRj
            UjVJd3hoMkcxb2JKM1MvT1prUzZoUDAKTLZiaTvdST+LXYq5M3bfRM2ns/e3kvWO
            ccqEB9OZ5P/9qJB9b4s0LLeaUwfvuOdydiDEsc0nNSCaEqi+ExrMTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:06:44Z"
    mac: ENC[AES256_GCM,data:+ewYc3kN9dZ/52BC89yrdFt2DnLwXVZSJnREfVtTflPvuJXkPK21Z2LcAOAj73PILb3DzCD7mpIxABsJ6alMcV3BxXdEfJ261Cfynpj2a8kVpDAB1pIWAOX4tOiIjh/OZFEF1DxrFGn1R3P+vsenIc1hz3M0j1lasSpOZw/Gnuc=,iv:hPHcwCK9OeswNflymGeTp1cdKcLhjhybhNvLtKpS8Zs=,tag:nBJcXWJmU7RZRBY7NAz1ag==,type:str]
    version: 3.13.3
