apiVersion: v1
kind: Secret
metadata:
    name: shop-db-polaris
    namespace: shop
    labels:
        app.kubernetes.io/part-of: shopflow
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:vOjt3oNcEw==,iv:5pLGGdgcR3GRXRsonqVXvseERF/Kq4mq9mQZswTJ4SI=,tag:ufNFjHtsoCw/SJtBsg/rBw==,type:str]
    password: ENC[AES256_GCM,data:nJz9xJ9MQarlxyAJ0dsVZ1wQrJPzlW6H1/HCxs+y1Wk=,iv:OxpYVLmqWDdUhGHhQyjggDNMdG5heiuz4CovdHEbq7E=,tag:RlWQzeHKOi2cQH1oDRYNXg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cUhtZ1M2VXFuemNRRkV1
            ODlVYUJXYUJKaUVoOTEvcjAzdWRyRGpOM1E0Cm82bkx1TmNvY2QreVRNTHNMM1dl
            MUp2Z3JzMmVia096YUY1ajE4dllrc1EKLS0tIC83NU1sb1JkOWpyVGJwQ3NNT2NR
            LzhzS3NDLzFMN000K2c0SHJUYUZCZ0UKMIot2NmPznXPl2tgeDCIyEIiLVN9BLNv
            +PiyyLFZ9qum1VeUD7Oxax43eS4p3VpMd7nCZIryR2VWyWCQeD5g0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T12:01:51Z"
    mac: ENC[AES256_GCM,data:+5AVMWo3rZ4PawJdInSpa+cOp/4fEsUxGVw5b58BQ/Nf4k2OI9ukMG1nZQ0dsRxg4FMapMvkbmGYQNaPG9mAXMlo4CXYq8pKu+OnFfY6JM98A3uSEjqmDh6HYs8+VshImSxtb3kdxbzgyHTXQe/Eu/WusKCxswoDUAubMXV1W6M=,iv:S73tjFKlyHd7HcOdaOHFU++umuQvua8FYhQNxqwTKBA=,tag:uwFXfXrldY+4UJUVol69og==,type:str]
    version: 3.13.3
