apiVersion: v1
kind: Secret
metadata:
    name: shop-db-grafana-serving
    namespace: shop
    labels:
        app.kubernetes.io/part-of: shopflow
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:NLiJD+e933kwzl7pDZ8U,iv:CAn8qzuA+Bfvr0r0/6R41po7da9UXtXsngmdYtz0doE=,tag:jSnSPa8BBp954PZ/aTw7Yw==,type:str]
    password: ENC[AES256_GCM,data:GQjJtBXEkno8OsT9ax7IG2i6iPa8smUm6orK3A1dUYY=,iv:sgtQcKW2IWr4jnemAhYc1go1ljc9Zh7etyvuswjmRcM=,tag:zw7Q9/vy5AQ/uA7QNJdhMg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSENpbGdCbkpiNzIrRW9T
            aElaMktibkR3UUZyMUEvWFNaRFAzOFU0Q0NBCmpFNFE0NndWR1BMa2Z5dXFpdHQ0
            RFZMNWVaQlZFaTc0M2JkdXU4QjlSeEkKLS0tIHc0VUZNQ1Ira1kxVVV6SDYvT2VR
            a3h6aFZubFcwTkZJTUlRYkhXVUo5bXMKFznCzMYb71mSOplbdrkitLtqDP6BodAY
            bkWDv7h6wpXGFHQMXGQowKfP2WMD8K5Aoheq3CNreSrmnDOYc+EEKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:06:44Z"
    mac: ENC[AES256_GCM,data:k/gKjGvT0m+2UAi2wx5h4oFob/v6XSBi7mwUqwbzJE/4/jxkUp12TFiNs3jQAE+pTBY0F5VKPP0ccWTwH4h3FwrQs+MTycBsOfMwp57AsyJMKCQlaMZzLgR6FzvTlaBJ/xCsNkzGbdFROPKwUkag9xiOZ0HHBlAX46xqDq+4h48=,iv:dfDTto6FKDk7I9wj3ikyWS1Om9GmLklJ4I6vphNXg5o=,tag:X8XNCyu4KRHV/jSPvoyQlg==,type:str]
    version: 3.13.3
