apiVersion: v1
kind: Secret
metadata:
    name: shop-db-fulfillment-worker
    namespace: shop
    labels:
        app.kubernetes.io/part-of: shopflow
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:jBpOylDYMZlEKrm0W7eeHc9+,iv:WhxSUDN5myE9tgeQnIuipd4Ekplg80pZG8ZD1Ml0Wws=,tag:lM8XgPneNRmeO9F3Jnkj8w==,type:str]
    password: ENC[AES256_GCM,data:fn03HNj+phEg4/ntwJ3d9gQ5DljSgGCFQOtCL3kwag+17u8+9wp58A+9YOmbRwbT,iv:CG7DFP8iv/FxxQLZowg25a5J8pO3+Inz8n1O3zJlJHQ=,tag:SGMtJjJzUAvtNXdT+CEYFQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrdXRMenBVNGh3elpyZ3Zj
            VHVHTU84bXV4M3pEdG1sWEg1UWFDKzF0RmtvCi9lbDR2RGNKVXRKNUVna3dJOTJF
            dzlmTHFTaG9Hb0Z1VURLbHJ3ZmZ1ZVEKLS0tIDVaOW9CSWQ0UmsxOGtkNGovVm9D
            Z2ZHOWFLNlBsVmtFQXpBNmFFZmhUUzAK26o2pP0mGRk4du0hUepvfVcVB+8zjU8k
            AbCpwfDpUT96Ah+eqCTQqkM+e7oiJXPv9k6VvJ3kk4o3VuDxaDem+g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T06:28:49Z"
    mac: ENC[AES256_GCM,data:JqiAfP61HUD8njAQqUhn1sBt3VsoHSXocsnSXBfb00JlhEg92vZrBkn8qKXcohuVz8biAM0pkME+YpKJp5k2kTkecRaEtlbfqBIt8CwkTlhBw3q9G3oWz1qPml2Vj2FpBttJg8Q7RGjfTN23VhLIngSZA1pdWPiSXwRGA4ZKyz0=,iv:t9RwC4FtySmlvrps2UMPttpQtQ7JOsUtqBvEdSnDSA4=,tag:FUWxLF6up6a4LCo716bkow==,type:str]
    version: 3.13.3
