apiVersion: v1
kind: Secret
metadata:
    name: shop-db-debezium
    namespace: shop
    labels:
        app.kubernetes.io/part-of: shopflow
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ov5J3M+kJF4=,iv:8iSFdT+6z4+GQ0i6WFx+CvyeYAp6qNYOCGS+ioyfffI=,tag:uPYL6i0i1H1soKYl/Jqlpg==,type:str]
    password: ENC[AES256_GCM,data:TG7LBIcbWK0THlpbdB+57O/h6ue/pU6A86xCGol/fT0=,iv:RuXqEGSVTshPgCsXfiBrUDf+Thgo6tSHAv3/JpgInM8=,tag:veO4dXUpI85EBL+y/CpVJQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnL01GSnpONGR3OHcwbTNl
            ckdsb0xObTk0OXJXckdSSjlWMlNFS0JNMlJBCkR6RVZZM21JNWllR0pySlhqRU9N
            WHZjT3JVS2NlbWpXVTh0U1NsUUpoL1kKLS0tIE9DMDkya3VXWWN6cGRxUTJVY3pq
            cEptNWNKUmdLWTRXTnlQK2dHUmErK3cKZtG9SBQ8J3IL/5qgS0kfiRfyz+OYpPim
            HQ8eo0ZdH4bKAU2nJ+dQGu4ybhc68ep32PC2p0e4liD88alkCCcOwA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:32:24Z"
    mac: ENC[AES256_GCM,data:VyDR9u/VupUR5CZifNPmEjtLxtcMOidbi/nsPZ6QJEko4HEm8hIXIOwSwx2VCwIeTdchBMtZpVX90peKxC7HCTa5NkaTPbPCqScrFuwL76R7Bd5kgGr4EehUqpK5E/5GwpytMHVkkZQtpue4fZ11CD/CEqfQp3TSH8uj78idCCU=,iv:VOMIfmZPhAlvYJmtO1JdMpJn561ypMaBTfoN7639wSU=,tag:23E6cMhUW+YYAN5+KVOa0w==,type:str]
    version: 3.13.3
