apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    s3.json: ENC[AES256_GCM,data:bHCbIxjbzpjSsS2SXYi8Hoc9v2mudX0Gv6bUxRhL9qwE4jBE3rz8QLD48tJ2xr+V/UwakiAuMxQsXLlIaiwZJfUhpAKp2F7rrr4pFy1p1wqswjpfXY6lKALivfNODXikC56NnBktscKk3VHGMXbsRO9t2rzVO8WnEheOjis3hWkJy9fjx9QYreWSL8LG+y0KbgCIyaQmxMGNw9Nf+48p6Ugw1AjkSikyUmXe435tyRlJL4L61BQPQnnJtHdBTyyEUW2Um4o2qo/a22+6wNjBSDiTl+Sb1xFU1tqrtOyE9x1GzuNbYws/eTCw1+wtjDaTFwvY1z6kPfsCpBLCTUyEMiKhVLLiPqEJVTVRflMB1vqp0oqfecjaar/5YAblqxWqkJ+M1tSVlaXz0knvNJHnX0btxUjCcWzY1+pNk+dF6AiGEIT24MTQ8HhNu6FCN0mslhIoK1OVliRcNl42sgkkXMbyzuk8b+kkhUYCiwBwBnX3FgJga6kZJImW2SyaXOvkRIF9kkN2ulFrNu18FYJz6GM8kthWIhoNOdKDYs+psWi1sEla8J7JK5arOW7nXT6DJ+0EIqpvXr6PZSv1wcBaJC6jn7mNKKpeQ+kKcBS0+HJjBaWgZvZeNQOPpXxEtSaFtZ5wYp5XVHIjRZa4xn6Y4I/mWZgdXy6z9qMQPWqqUmw990JcujxzEvj+k25wkaA5kWdJwnMBZ4qoxwufUoLS8AoHF+XG7Xypez3qQ6RPqjGowc9oKsldsjqdApopqy5739aRhNVsFtr55lu4EF9kjPR3V245XHHbDm79u5fyjbnGFBvkhBWaYUt+9649kCqoaQjhhOHlw2DceRUDdUKlI2dcevaIbi061cjsd4JSwdnsly+bI5IvBy531kk1QjYaMtlqiUdMimjikjYdagGvw573msd+DcGHUCbAj4WaQmfrAniALJajwiuRBnyyyOxnEb4Tq/8BzDVmNe5+qTVzpWlV+UmvMXP/SKLhRY0Hgpv9v02uakx9KnFVihZ0qwdDcJJX83v84wIhIk5GyPmzo6bO,iv:NlbDLvVWOZtVYomA1Xri3YCg0jdYlJdMBIL9RF4GH6c=,tag:BR0jGY8QgMGz6b2g7mz+nw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvS3A1Zllxbk1wbmpESktC
            Qk1lbEU5dEFGZUhQbzlVdktDamorUGxROWo4CkNSYVBUVm1aSTFqN1F3WGxvdkhp
            Wmc3RTQ1YlpaQ2NNQWRHbFFxRFp3K0kKLS0tIE5CRUl2WDN2UUlPOVJiV1FOLzI4
            VDFWYVhtZnNwNzZOZGRvbjg0SVMvRU0Kp+Ger4gSZuPbE3tYlkVLKqjCmx9ubfJE
            G42Dia3t//iVhYNXtshFm1vDzhWElhpxV/3esGKhDQ6QudEqnmL48w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:31Z"
    mac: ENC[AES256_GCM,data:y3RxK8rFTbEtj2TN9rSL6SrH4j+Q+GEoV27CkDCyah5r6LnFlv6LyTOeKEtJklvdYYGdWz7cVQYt70k4y3tvrxO0ts5u/I9a/UZLALrLgq0M2z0XKSgG2aF7sbKZguq1pdfs8xVSUvi6bkeB0tAvDZL68lN+KWFKujJgrmMBCN0=,iv:zcOyN2qIYblxc8haNKwm/vfOm+OOfVLE03S0uX/J/dQ=,tag:uTfiWHuXMpFG/aMITkZelg==,type:str]
    version: 3.13.3
