apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-cnpg-backup
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:B0IiegiEsg+T30GJGyObNPUvriw=,iv:z0kGKd7wTbm456ZrT88T3rZZ0eA+HwyswNsScDxFOuE=,tag:bxJQyCBLkX2+qWi8pHG7hw==,type:str]
    secret-access-key: ENC[AES256_GCM,data:setKtsq6qflBGJAueIUMRCCscXL6EIHRi9jzNef9sBir/rw8ywAnUw==,iv:7eFM4lNMaHue1PjmOvO8wQNUN8bJYt3A1IZ/ddaLonM=,tag:GwNSLDsE280MbjFB0VJCWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRjVqejBrT0wzMXdJVEE4
            MmY4SWc2QmcwWTlUWHNFcnVIaUVSeW5SMmhzClIrNXZIQnA1WTBFVmlIbmF0QzQ0
            K1dGWFFLUjlwM2tmMENYR3ROU0VDRUkKLS0tIHVadDBSaWV0Rkg4QmlSYWFOZk1s
            ZTFpWTJnRnMzY3cwZVM5a1ZBUC9ra00KZmpLOmFOyrvoKCyp6sdVaLCV6hZH4+nb
            Nn+68yXF6OLAv6CcopRnFK5AxcgCtSm90dJR+SIVBRG1sdcJLCCy1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T11:53:11Z"
    mac: ENC[AES256_GCM,data:9C4ycrkWDJcmfXDTu4mTNCDrXo6ZGpNdsuX6y/gRE27Rv/VD+U7QOHr8fgot/37pXQZirjK/9AkR0fQgR8tfVf6C0zvMJxSxldqf3UwsogCP8DNv+xm1afdMWuIv2gXu0lV9yIBFn2GNnKq9BVEU8NAJuQCYwvyPnw92NEVrTjE=,iv:T5ejifAUYYbgNCOTcggtLG4mpjtIsYKvEyzwjemOggY=,tag:I0UrIKYYBwdPpsbTa26oUA==,type:str]
    version: 3.13.3
