apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-config
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    s3.json: ENC[AES256_GCM,data:GIzRRo4T+kLR/PgL27+2GeGMpocRRlKbyH1x6TzTNra0qpwaMSnQQoCi6yZZ6uHLzE/yF7vzc+chvKfmsk3KVt75vWTh0UfRRWUfneUpSKPNh3y1Wt4+jQ7oYQEKc8xlK2o39//HOHNudCFsFj2YwIc2qANFOI6k3hpJgt20cafgEYqbCcs8fAE9NU87YlQuUb7TQIwZMaNCXU6GYVhakF1QqopDsUKEucDecwYVnCKQZjSRHIiNfqfUNAuzkc5TG6jDB0ymchQCw8Hn0z594KylOSnbTWnmRteLM+1sA3nfeh3Dqx4bRyIsBmTNLHfYYdSWr6ngxNeLTLT6eG4rAX+rUoFFcY2EDJVQjdNYF9t8xFc4Y7hd34S8Zotiyie0RyJ9z1gWT0lPTKT7VkFE1hJmZuthUvT57BMBcTI6X/GW4MPhaOkGG/rPUoLGjmSLGHVZU7aKPaxbJTVYA5/7/0jvRqDTnOJRzuDjqrdMjUcp8lfW7XF/JjKhOoVvlpvrgGRVw+XOLym7E32KH7TlwG0kNfLORazjMJRr332rtoR16QFGe20BXLotJQnjDQYHzRYd6vggq8y0/82qyFrEgn837T5LWCtVkunKbooXaI69gd3gfrdJEOdtq2Umah44i3g72V/OurIghmtlDfuc3B5m2ADuNDaJ5Jx/Z3H7reJ+2xq+6qNPZGpc7Y5PWh51yeJ4XOo6YxZFmxmmSkg2LY0fZFLMBcVn/OOjMbQf8FH/4PldJfLUOWpj+afGspPfLWBASGDyHlqGmMtdNA94W0aKJ0TrWm3vrK8Kd1Hq8VttNRC4oiK88wHNrOO/s65iofnA+nIptnWhAFS3smPVLICM4AapADOCyxiaOJD3KXNLt3i/4jpSIGM5D3KPiv+xnH+8/5UsJJZXn2WQXEcd2dKQ04pVUGNnX6TP+q2wmDpwKbROmiuYi4EnIHmGVEOK9y/0VCyNuGxACaFRu2eazs4W4JTDKBu+5rSftkVyY7c1cWZstxHiMCqo35SkXskNv/4+7h57v9eMAP4OsP9Hq6lFBx7k3MgIlzMflRlDqlTZG6YsW0uKDdEnAcR6gMH9C4dgJzyIN7aR0frON8ks9Y/wzrfjK/nZ5Y+sDpFHxNhvnGNqxhFcbHrM6QjgnNJS82DlkfpSJV2yv2xtuiH3fdpbZhgZvls3G9MJiPmc3Iaa4CKYYb3skaxAWjIDTnJ/fbFHKOcJlxfjxXzwW8i+aeNIP4tvTH+ihcKDgTrUdxDlKgoY9tn3pgw15mPavIUEaZgP7subagGnx7nXJexWPM4Az5vj3gGLqKpeSFC0tRtK+FnrKDmMok12,iv:pZTFLqNqhFzyqdqqV5lmcE5HUOrBL6ci/KvdlFsFDgA=,tag:MQFGA4s4nZcPH53TCsg4Ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZW9wVzMvKzdqaDl1UWFX
            ZTdUbk8zSVhHdUZ6SWhMenBqVGxZbFgvb0JvCms1amNHSGlTaGdBTjgyZlhwQ0lB
            YnJFVnJKdUlSOWlmMjIwR0RHUTlyK1EKLS0tIDBtcTdzTGFoYWk0aWtWRW9zWWF3
            ZzBYRTBqRVIyaWtwc0EweTI5UkdUTUEKSjxUbXeqJ/RlQe6jT6L3zCO98phokza1
            jBqEcCIr65nRjoaAD0GSQxP7My3ndMv3LtQb+WJZcGwdiHADfQhT3g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:kC4XupQV7/kX+i97QGiqiWFmqmhFXPqYqyw73feAV20X6jX6L+58ZslJUDHINRlFwHNE7myTu2wgYByTC5QyHyAD8LvFwxZiCSYAO0lv/OXQOLY0v6WEDJ2mvrEaz8LN7bSMzIOpzV4wlZ8VhKiJq/vJn+JzZVK8d4tF+kdeW78=,iv:kQbAsxU0n7K5jH38M7r6ICV71TyVVDzAkhfwzn3R2KA=,tag:3VGI3j3+NSn9u68V6EOvFQ==,type:str]
    version: 3.13.3
