apiVersion: v1
kind: Secret
metadata:
    name: flink-s3
    namespace: flink
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:nvxLADFB6ExS0Mxj4LeB8pPSGR8=,iv:9n2oyF6GQ8/wUwVkGnj2jH9FGFt8faF76qJa9Ij079s=,tag:N25LKe2sRQfTGosQHvM8CA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:fJ3hEhxsfaXfFbitZAaNJ6gXXy2veH0tkEYmLG6EKoM5dzVzy7Lj/Q==,iv:feRB09/e6vpSdDz6d3SUrJye+PeFa+N6RNKjy/ExTgk=,tag:r18vRlsHIGv09SIPRgS4HQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2L2FieTFsWmdsUVhuNlQx
            dmhqclpvTmx1ZEZYTytBNFNmU0lNd2hBcGtBCmg0bWdvQjhWK2lnM0hPYlNDU1Fp
            NjRteVUyejY5QnBkcSt4N3VRTnFaNGsKLS0tIHJiS3lxVW1oZW41M3pTTTQyV1F4
            VG5JSXFWT0oyZTZYS0VTVU8xQzdIVE0K3WT4JuUEo0G61neG4861fQH2anCRuIGZ
            sIK/TdNkWRL7VJyF/HHioj09sE+l4rD23QhLSwqM4eMK/yeiAWx2KQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:wpj0ZwiftU/OhgnK0sCP3SMarKlSxPFAYtoe8FNxwSL1zg/KVE0v5DDZpTJhEeebpg3VCdGgvsxiHw6SR/cWgV7sZoBg9IrNJHoa7ZXVWbfvHj953bsSHFd8IyJFlFgcxCZdPG4WEvmTgxSaXvKv0ELoT102iAHxzxzS33kINE8=,iv:9sNpoEl0830j1zcKdoqK9Aal7IWPRWzjOjQa+eWJcHA=,tag:KsCKe41Yw4Kyfj/REyXo9Q==,type:str]
    version: 3.13.3
