apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: observability
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:ZFgEfrQ=,iv:Xt4AdPPsLms6caCyvSZ3hDzJOF9TZYQU5y7GkXwsr98=,tag:YIW52LcatTL3Abk418JZBw==,type:str]
    admin-password: ENC[AES256_GCM,data:6+5Dl8DnPNAHWf250yNoalAaikN9F1V+kWi/Vu2RVrs=,iv:9tPPICNNzu/RD5xwa52FlFkNxhgpEDQoCUh7iGDQ+Q0=,tag:64YmrFlEwQkDXOBdTMq/7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cjdVMis1SWxIMENEYWw1
            V1FvbDBRWWxpQWpXUVR0M0ZncTRuUnZHb2h3CmFMTUhFQ1Jucld0WWsrVjRUenJM
            aWdDMUFLV2srdERNZXh6cVFBOXdXTEEKLS0tIHlNSlQ0LzdmRURjY3lBdit1d294
            Uk9FRXBNQlB5Y0ZNVHJCcStUQVpFN1kKbg4PDQnDIUzZWSYKvIMFdRhXOs3d838v
            uv1R/ob0i6MAXgx7myR5z2FS0IRYBVK2lxIldRC3rzl3/20W5xLbuQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T11:37:25Z"
    mac: ENC[AES256_GCM,data:0m85TD0yIyTVedO4JjQjPqTtRQ59mQlVgssbz/WBGUk0O5cZkzI9+1cnh6ZAraDLH8/PEyHfih8Qcv5MGaXbw7EXhSMqe9DhxI7UmakS0EOx6g7LyYGMojxI656718sXWKlK0aNahCetnWW7Aq7SeFYnraMc6SMPC+E77BB+/uo=,iv:vR2FrVN4mjR3sCV/A1MwYWbvJbSMKY6oPL+1gU80RfE=,tag:JomCyOOePOvYAcRd+izAxg==,type:str]
    version: 3.13.3
