apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: slo
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: shopflow
    shopflow.io/profile: obs-lite
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  sources:
    - repoURL: https://github.com/winthebest/shopflow.git
      targetRevision: main
      path: deploy/platform/slo/local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
