apiVersion: v1
kind: Secret
metadata:
    name: lake-s3-trino-ro
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:vP5kAFml9dZez4xZIAhrUozjcj4=,iv:rh7RwxBq8HVIS82zk3z6OuPdnMYOnwIwme7zQt6IR0Q=,tag:EfVu/JhjyvnX2xt3miB3EQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:gYl0SRnGz2DQc5y/cuuAMYK/po+Sr1gBhzoupH58FWMOECT9A0CGJA==,iv:Rcsqm2fZr934QHUGHYrh6ROBCAacl8N4UpqeJCtB+Ag=,tag:qlJdviFtr3nJpDFA1MCcww==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxdURmOGNZemx6NzFLWmtI
            UHdwWHZlR2NuSkkyeFBBT2EzSDVVUGpRcEQ4ClJTN1dXRmIrTnlpa1RFbzVJLzQy
            MFhhNFVJc2xqdmwyak9ieHozVnh0dEEKLS0tIFpFQjIrTzJueWw1WEQrU1M5ZDBh
            VEVIa3I3S2JuUTd0Wmk4bTZnQ04wYk0KqLGToYBfHUMUWc6SgZYQG9q9dWndMqUF
            DRxZwFUrbWSgL4H7pwDsTtDh+LQZgpxDsy1zeP1RP2CDaG/8zyuwxA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:31Z"
    mac: ENC[AES256_GCM,data:oZHsJC+i0jyRBKzjTuzGadGRQT7/3xC4C0x+44/Xnnseaz25+el8/NZyNSubyAmbfLv66QDWkSMdc3P3CSrlIG463skXFyyROKxOPmAR+jxgWR8TCdWvfe4ZSGkcUitms0Z6EsrsOYQNZ5i0wvPNQKY62jaMcd+aPx+JgVy0AFo=,iv:KerLvmLArL2SIba9x+IjmvZryl1fxFjpro56ESx1trU=,tag:ZavHLz3PyPq4y3repHdgZg==,type:str]
    version: 3.13.3
