apiVersion: v1
kind: Secret
metadata:
    name: lake-s3-trino-ro
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:QY+VxKFVyOsINUYcQ6/lKoIJR3g=,iv:8IsAcqmS6n4qlLYhPEAliFTyYBTX2LKYPPdvACieRKw=,tag:syDU4g/iGp44QJ5KNCzQfg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:Ytk7faVvmrsEu/SQ8J7OVPyWQ+HNPrF2wfCPM6UBqwpzQbgbX1pXFA==,iv:IrHnGf3ZGDAplc+0uREN9JvjVxfCTSNB0xuWAAH62Gc=,tag:pJWasnBCG6s8ERz/W+1LlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMm9oem0rSVV6WnkzTXJF
            VjFtNThodVVqSktLbW9SWTJWRzJUYUFNY3ljClBBZzVoWW5OTGw3N1hxaEpkclox
            cHd3eE1zS2ZHalU4bW9ZZ1FFRStuSlkKLS0tIHA2TG8rVDdwVmJ5YzhYZWNRdURT
            TzBocVlhTDZpT3ZqMVA4WVpJdW9SVEUKN0gcQtc3goW5jfdGyYPGogqvI0uAQUTi
            pJz5V5cjYnlbFXuDUJIRTwt+x4yPfbYSRdxuQE4VjCAzpDA/Zuwyow==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:95YcjN1JG3+ZnVLZSQzGKE6jPE7blk3Wuh5idw4xD8iuLqClykQCZEPwv0HsvoM3uVV/wqn4VgJwJ4xsD+JgLYf5N8wXoQ9dEXUssmnuhQmnxhBDVStaNy0YHL3/MUwjN8DDrho6q0W7VxrRtx2fQiddhiCvPWolnddP4vE7EJw=,iv:txy0n730LRrDfAEUnhwWqqoqkPyh+Qbn5Hk0iGixdyE=,tag:I5ZPHRNUl6rBsLOKp1KbnA==,type:str]
    version: 3.13.3
