apiVersion: v1
kind: Secret
metadata:
    name: lake-s3-trino
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:39vJdSjbtfb4U41+WcSnGjf2cAU=,iv:1hLTCMe5Dc34tPKjE0DOQnD2vGjPL3/FzEHpDFmpmpo=,tag:nnwG9wuvYHu4KLJMRJ/CsA==,type:str]
    secret-access-key: ENC[AES256_GCM,data:sp7vVXFvcVpBU1fsk+tVHAxL3EpVcU8E8VHw0AF5Ipeoq6rKKpzoog==,iv:7fS1LKXoCD7JIQw5kMSYFXXNKGlidF0cZ/y1v8v6N9Q=,tag:CSXa5YNtXPLXydPuvhtsTA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6UEVlNTZPSC9FMkhXQ1Jq
            eFJDd05EMEhLekk1QUlUeEFvYmtGVnNtWmlBClVtTlZQNE8za21qdkh1UXJ2Y1Ry
            Y2syWlpsbVdGNVNjbkg5K2g5Sk1CTG8KLS0tIFp1NDBFaFlPWXl2TmFMd0pYU3Iy
            eFFZR1RkZ0g0WHI2SHNrQ3ZNZFh6TVkKCe0Aj5bjrpmgLCAQiFqaNE0gZdzya0dM
            e22dWdbadFTFIwpILQ9neeT0yvJXF1OFEv51eHM3MWPJqafZEnl5vQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:31Z"
    mac: ENC[AES256_GCM,data:eJ6IWsAYar2wsz6KbyMaNSwE9diT9L/Gn5CzKCC90AfOODNdTqTvCYDMUNiuSSjm2rIRvWcyEnJ/xAoFMNa+OU7g64jpGPlOMXLCewhG5rSk3cFT9eiuunJ0HLcp2+uXJxKHI1gvDi54YAyu0LgwScyPkZPq53B87RcbrDSPCj8=,iv:ixZPs4ZLuOMktx82k+yroH0amHNxMVs3bpllLVvO4f4=,tag:qKw1EHpH2RRNSfT3PoZpjw==,type:str]
    version: 3.13.3
