apiVersion: v1
kind: Secret
metadata:
    name: lake-s3-trino
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:guC8dzffCa9p1pM8jDprLwAzJ7g=,iv:+uLB38bhmDjB7O0i/X47Rz3lYKeyxSofGa5UciM1Ncg=,tag:WUX54eADfIAwf+JXAuFOmg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:y4VN1IXH5qNEKAXHwpqam8q01YMgdsdKSfZDOithhcDt6KKrbTAwgA==,iv:POKgAtxJAzlMbXag54bx/HcCupb5ht268eR5oacvFzE=,tag:9UWwwKyBEn1hadqc1lISuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcnozWCtKZkUwSmRwbDl5
            R1BvaXZNanpxbUptcnBQL0EyZTlWcmNualNrCjVmT0dGeHdCb2FaTEZ1RFFGWG00
            OHhiS0NkWEJud1hpa0l5L1pXY09aT2MKLS0tIG9PZGljWDd5Y3g3OFllblNyTzJ5
            QStOTEhha1JpakhtSGhTcUpJMVZsWFkKJrSXiSkj3RYr5tSE8NgQDpO5i1hwRCAS
            VJTMKR4w/yavnzXKdQW9WC8eXkhNJDV5u6tbdRPyOyBcFqDB4ftF4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:eBD2nEL0kaeT3RI9JFZ4TjluzsmQP7wzDG0xjS2Ms7ZQVF4XicHE7gvfsAu3Of6zKwyqqhptWGrHU78OGDV4Hay1mp7GHaK7O2C9qgZfRu6avL+kdlyTmZSLfv1qmpyeX0oVJjvn3ibswnUl5ZC6zgOsZ0ZK8Ppp7NQEzoOykrE=,iv:fzzODrPrDwfWXsWSbTkw/Eq32q1JnTFlu8BrHsuPDKA=,tag:sjn+63fDf0jWAD9+LlQOOg==,type:str]
    version: 3.13.3
