apiVersion: v1
kind: Secret
metadata:
    name: trino-password-db
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    password.db: ENC[AES256_GCM,data:kD2a22Y4Jko6sXYAuwEhd0+fgBGJZksY70wKdVraYGVDJ3cK0WGuC6V3IQuvbLCXKRHG0H5WwNPHCO7qbmw4FAYr0dv9ilAfyydyrg01BEcyNeQhX+7czicgniYmpmZGbKPipeb2O2Jlv+njH4EtxeJ4v5XEIXBBmZPO5bn3EHPobrpZ8Is=,iv:uDutDXrkNTvLPN56PQPpB0q1SmtlWyostLOtuIOpq0A=,tag:Hbh0m0A/7pzqXkzjHV2gXQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZDM4YllZU2FDY0ZDcXlo
            TEovczBLcGtiaGhXTzRxVkhGYlplQXdSQ1ZRCkVYN3p4cGJ6QTJ3TzdSdHUyYTJM
            ajZJRjZyWWxCZTJrNFJhc1M0Q1Z3SFEKLS0tIGJjRGdYVkxkY0YzQWxOdmxtVytK
            Yk4zV1I2YWxXWUczK1hDK0IwMGtlbDAKE8NOcU/QGTPXVL6j7ENO8+Qo/ULkiYS2
            vErKggorbqSMVyfEmH1gSjs1UzJriVfDrEZECbSkWdscfOwHQIcFFQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:aowghQAQ3sXskQRdE7nz4VvYHiEL/ZxDPIlCe1fKQyH0zOLIzV63VA754XARtoenOBbSuXKm+ye32RSBZ2j0hfx33WaXz7cMTVq7xPyiEdDB6M59O5AumyF2OnSuxUrKEBIlUTqk2me1Oq18W/hWyap/Z/CKNckGbMUnlXA3y7U=,iv:TJwAk01Lutrzsf7KYlI84OS8IUtlIX0UWNkwszIwvLk=,tag:5J1o3PyIYEbrLDABQtmPGg==,type:str]
    version: 3.13.3
