apiVersion: v1
kind: Secret
metadata:
    name: trino-dbt
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:eMpj,iv:1bXR2fcT1uFgDBCJwZCU+8jRsOqGR3vCghGoqRW/xc4=,tag:DOzieqmNsbkzvdRS7Usqtw==,type:str]
    password: ENC[AES256_GCM,data:Arozx3HWyWMjCPMP3T7u/N3EE2scvwHNzM15H+bMAlmMP4sOcx+bdioV973MUHBi,iv:nbcdD2P9BfC1x3WAIO6Rh+XKOsUYVoEuDHRUy8z3Fgg=,tag:pFawLSmF1VIN+214XeggAg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRVZKMjBOazBlWVF4OE5t
            Zm43OUYwSTkzYXR0NEw3TTg5aGJ0Y0ZpRW44CkE4RW5SM2Z0TnJYRjdDb1FiaVE2
            dFkyOWFpeTljQVQ1VnJaWVlieVBkb1EKLS0tIHZOb2tIWmZXUUNhejBwWGFlNTJM
            L25rWVAyalVSVWtKZ0dUcVVEcW02TWMKcQSdWTGlgaUgDySN2Tv/l6qlX3D+2kdq
            OIEMXYkPFPpv5tYCjeo+sav043k7vDb6pzK2MdDnp8aK+Y2KNNeh6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:31Z"
    mac: ENC[AES256_GCM,data:376lsNn8QDAj/p6AbiIQbUmF/vA5zKw94Rifrq8DAZCt/JJux5k+RQkvBUWjS6+yh4Y4ZIcjB67e5vksCNkBL3umZnYs/3omX10kpiwymY3LEeAv9Qx1XatEz0zSpWPeuqOXb2z44gMxVE69E8A/mvXTEmk72uefk44UQZWSM3g=,iv:4WxwzOopyiYbZK29+v8NOHnf6BkXVsxitS8dRZcKe8E=,tag:RcK6FtUZbvbwRVq4f9zfrA==,type:str]
    version: 3.13.3
