apiVersion: v1
kind: Secret
metadata:
    name: trino-exporter
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:AMldmcG86tk=,iv:NgTI6tQRCCKMTD37FNWMw8Xv/CACjBva89BE+RtKk3s=,tag:XZ0SyJ+U3l9/LvVmWX0DFw==,type:str]
    password: ENC[AES256_GCM,data:vnOWlsfW5I/9zjdfOh6DRm8ZWV+Wieqb61O8eYbraZCQumDTKKAVjLNdJPTlTW5l,iv:ouywD6HhANJVsqbJwkch4+2JH+NY8ZezQLVW6ZKUkLs=,tag:7M0Y7C2TCyOsJSGBTkj+Lg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M2FQdHUyZlpSSkdUaXBq
            cmVmTFAwaDhYSlpwYVc5ajJkdy9zRm1lZGhnCnFMT0lFWjlWRUI5dFhFV2NWM2hJ
            dGg2ak5HZnUwTzFwNStUb2paZ0wwcDgKLS0tIERqeVhNSkRzNUdrQm91dWhOeWwy
            QVhqN3VLWlRwVUJmTGxFenMzVkUzNUEKq9d4WUYXa5ocm59Qz74MDLfpKJ7p8CHG
            +nHT2JB+egGH833RWhyrW5MqgNnwYAQXW4vwA81AvTtG3pEXIirxuw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:xPFl+DVPBcwpP3fe4A+hSQ2c86CFkvF3MbicsOddHYrORV4PNFfXUelfMeC3gFthbjCZ3JI+zM9w6DGGyWsN5w3dOiqvF9Xs4YdOaA8q9jc4aKZSuC8QW32BX5csdpMTuFIobSeBHNa1Ne91Yvn6LUY/C8l+9xtIhm8EzQB4dAM=,iv:++MdcALYMWwPzCyPwqmRDRfn6mlhMV3zfr8Ddx0Rtg8=,tag:Jz3ijbj+z5Ieq7WVgcznIg==,type:str]
    version: 3.13.3
