apiVersion: v1
kind: Secret
metadata:
    name: trino-internal
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    shared-secret: ENC[AES256_GCM,data:xb0N45nBCirjFhJWWimSMK+o8y3qSUWdisaOYz36psj9jfI/nLFKS5T8hvp38bqH030bgXcd3pcDnp2JfsS2YQ==,iv:Qzwxa96BTfwZqAyW9I6QXvM5IqVBorKRIiDev2mVQ8g=,tag:YAdwZhH4xFFObHYtJYCtfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZDR1eWNxZmh1UEpUL2Zs
            TnBsMkQydmFuMDROS2Y4dTVKb1lVK1dkZzFjClhBb05XT244Rmg2eFpKTU14bXpt
            Q1JtQ0k3TEhEV1JNSEZCYWxhcEdvVWsKLS0tICtzMmFWU1pvZk51eGQyREppUVVT
            RTN4VVBZVGlZeSsvM1dmUHp0czI1ejgK7XErW9km4FFBJEdZHrOrfbZg1QJ9cOol
            KJUyGjkg4Ijw+4tS5WyLOjJO0mX2RphRQHXiQK7GniZ4rx9EBWxjDg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:31Z"
    mac: ENC[AES256_GCM,data:SvLL+t/lvB6IZB3SMKVQTqvOBrXh9ZgoAQY01FiP0C7oOCDUWRJXF8umwN0NJHAlIfLYmvOdYToSyVq4NF0krYhKMGmNvF4OnIXWwTLwqW+YVkyJP6HS3banznHGZa/LzBmdc7OI6Y0XekL047OH5fNY7+VJTDInDPoIyWrKi0s=,iv:V9Hkm3rPzEpxVyc1VaG3Pbxkc0s1Zz+I4lZ63Ocl7hk=,tag:bJRw7zS3fnmcd6gJQ9pQcg==,type:str]
    version: 3.13.3
