apiVersion: v1
kind: Secret
metadata:
    name: trino-password-db
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    password.db: ENC[AES256_GCM,data:/1+yiA6ymg5V8p7x7eWp5ly/hWYYo33zRxovstgjBwIe2kklqQ9B933D6xta2l46RSdA1dqMWCe4CRAzK/OzPoz3typJ8YtTW0c3MlLJ5I69/UHLybFKlEGrusWx8QFvo/nMSE9j9zw1vWHgzvUocBtTFTbdfvtPfYapKxJ23BAmHg17q+k=,iv:svAt3YOW/xeNc0tchqBTh3U582CtGlZhem0IqIlxQI4=,tag:00q1UCOBVIF0H+b3LzfUGA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVOEJkdmN4WTdmQmNLL1VF
            KytFVm5yYWt1S1YyMmN3dWFHaUJveE5pSFhRCjU1VHIvUWFsYjk1S0lNVm5IMTJi
            T0g2L1F4Y3huMURseWhRWWMyRzMxS3MKLS0tIHBkbFRyaUo5WkVSZGhsRXhsT3pY
            SEhvazd5QnliYnR0KzBudjRQSkVESlkKa0aHF70jCyP8psJwUhWnncOGmEVx+8UW
            pRgNr6lMCH1ERJ9ypeCvLdYniVqgVoCKoV4m7B8aTOTF+FxrqWrG9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:32Z"
    mac: ENC[AES256_GCM,data:V44WEykKzN7bG8Xdaz2OsKTZ+HMzzeKyttCElhtyIA7TY5Qo8WO8EkoSiGuskdVTQ3t1EcKCylRW2rLLgZDTkpZmVWgzecocRngL88hlUOI4lM3tOLlvXlccRKjGHVdIWqkWnuDbH4aeoBxUQeUj63Knk2hdCzSXBev6GfQujsI=,iv:zGqP/WGShvHu5SYiVH0oEf8b5kOk/PcLz+qAermgRVE=,tag:JqSYQsHI4W8F8Lu+stcFgA==,type:str]
    version: 3.13.3
