apiVersion: v1
kind: Secret
metadata:
    name: trino-exporter
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:30Yq1/J01qU=,iv:zVZj2OSkG5/ZPHUsPuTEqP5W1bXmgIhESw6AlnaACr0=,tag:ud3h/iPQM1S5egBPaGfeDA==,type:str]
    password: ENC[AES256_GCM,data:YBy6w4pcw3qMdoo1PBBp2Bn10DD0DCSHlUjav1D1QNlmxcIm1gf0CIltB2prJtH7,iv:zlU6feqV7hpAl7eDaXOd0cPbpScbfNpjFj2ui1w+1wY=,tag:+w+gCf6+RLC7o3wtcvqCKA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdHhjUFppZWpuOUQrSmxJ
            ci9IN3YzN2Q4cGdQTy9RY2ZjRy84SDBpS1RVCkhtUzFLUEZJaGNvY0JzK3ZCaHJL
            SHNCaDU3dkVlZnZDSXJTb0lrNkNsRTgKLS0tIHJna3VBS3lObG84Q3NXbFQ1ZmF6
            UHk3bFpONHZMdjFrNnRRaWg5NThMaVkKDUdJBswvOb61MO1739WvC0N0T49Tgrxe
            JkpH84M8gPXF8zyu4ETuPNw5y+xSxl0ncGbm9xa9NdnSgpi+4rv6qw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:32Z"
    mac: ENC[AES256_GCM,data:my3WdCMRtZ5lulcYS/fMM5WwW96Kr0J5yg/qo7R65YU4j59ixJxW1PQlFNNtYY/5yURTWhiR2L7Tqwl1khABnjMqQoM8G0hcqP4JPA0772ZGCNIK/iikzP/YV1vA9Aa6TNWMQIHAx1OhEAqvWhDFDdvOwOGPAq3/1bBhdCEn618=,iv:r2kkMl4peyXPQHZmUFB/BQGzITYl8ZkPIgbB1eH/XCc=,tag:ZPoT5Hy67IVh7yd/2w9+Xw==,type:str]
    version: 3.13.3
