apiVersion: v1
kind: Secret
metadata:
    name: trino-dbt
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:LRM4,iv:XCX9Unzt6Y9gkRHtuv0CBEadZSMQUM9IXD99Ld8u9n4=,tag:jMQuR18osqibQoEVxItxmQ==,type:str]
    password: ENC[AES256_GCM,data:2GvSwz0xpOqMbzMYUXWzL05EVXVgVnLfqlLFJFRuU0AGh3d7JDiY1kU8Ded4Ix4g,iv:18iAj4t/eGAsG1VTKQZlrdNbDSZIZMXdlZV+vWriDDI=,tag:+lKYfdU94cz+9nPW/b0uXA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMVFaNTlDVmJWejBQWW40
            L1Z5by9pNHdZRFlSOEpQbkZaU0MzcmFxUkFVCjhyNFFvdU0yeWh5TExDVWlNU0lh
            Ny9CdGUvRFpSc1lSUFJCdW5HcDhtekUKLS0tIEtjNSszRFF1eHdRR3dwcnEzdzV0
            OE9adEQ5NUdlejRZdXlGTlY2bm5aQTQKVl2OR/e7zqtxYvwyIX5Y/U1HtJP5gDU1
            3zXQW0/sAgOY1e9EcjOcZEWp4f/NfCHUqVPsIf+8aJB9xjaqg4ijNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:xAHzxGw3ZQ7M9aMExkwVkzfyUboA9UB1dQd9cwWpc8q7ZviKUN5CBhvQCmgZ5CPsSLkIu9PUHdh9eWczmZVA80N6H1GjsQCCsNL4alYXiAU+Jv5+J8yc/LH3NCXO+JIzkDoX9g2uC3ua5hip/kdXnJPBCqLyr1MrRFwHORbimuk=,iv:a1pyYDugQn8i1SZ7lzGG218v5rKppX4cvt07sbEa1UE=,tag:hhu0teXXIS/seQzT1JcDPg==,type:str]
    version: 3.13.3
