apiVersion: v1
kind: Secret
metadata:
    name: trino-internal
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    shared-secret: ENC[AES256_GCM,data:dFd52iX21vQ/KCdi4+I93AEIzZn0BKpN6jSsnnEpFp5W8A7oc1LnIKgZbeyB89F9N+Au2q7woRzNnMZdVp20yg==,iv:koMh0Rb0LoiuhNIQJci4pr/3TOmDQ9exG26njnGxzts=,tag:hb4gmLGi9IWWcunQuuEwhQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzNDVSdjkrQ001N1BPZmRF
            akZIUXdPcnhJSUxNb1NUZjRzZjJycnVqWjJ3CkdBU2VnN0U2NGY3Z1Qzc2ViRFRx
            bDc5NVk0ZGVuL0FUa3hwM084V0Jtck0KLS0tIDBVUDBSTzV6UHkvTklMOERRZ0lu
            c0VDUjJmL3l4bis5VDI2eDFCOHFKUXcKBHJVpglU5tsF7bkWnbPByDYoTIJ4YTYC
            1k7d1VBSbeAd3+LEIBYb4PeUK+XQrZMVtmooU/5A6xBdMWre+Ljpmw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:MyeKfa7/RxfbHIGRYVlh1ghwbnOgfVrr3EzZC8kkFDeps+E1fygL3/3QErCsjtemYdSxud/xAOiGnDmtrZZLuMur1Gpxgke8vNWvTh1A4BamwTl8sx5C7ovxuUc3vEv+gHstpINMVqfQGZ+xHDNbyAm/VKQ3tsSgEuUZLl6ztGs=,iv:dyPR+eVMXK5XLYlu54mnjPDcL7UWCzdP7CRqrZKDJFg=,tag:oew3VXZI2k54gV+1M41gBQ==,type:str]
    version: 3.13.3
