apiVersion: v1
kind: Secret
metadata:
    name: lake-s3-iceberg-sink
    namespace: kafka
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:iZUN6Htk1pSEZXN/za7urmJCbko=,iv:6CJ43fCV1CBNb7rgA6z311oWVju8tQ2MgfBVe3vh2tc=,tag:vnSIl+B65zRmfS9OD2uUGg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:a7CPhDpnF0Po3JeWvdj0rgd+MkEr0nXr9QOTad5FB6vm3UmPZ1LQBQ==,iv:MQ0DXvED7CKUmcJ7FsN6LXjnuRDQQIfRkS/Ali7P87M=,tag:8vdH4CU96UKfLXQI131oMA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRk9SZ0c0Q3hESWVSVWE2
            dzY2YUJCK0RKR2xQUWxEYllBT3hkQktkdHo4ClJMclgwMGwvMkdSNlljVUZQdXdR
            dlJveXpoMmx1TkszVG9zNklPMDFmY0UKLS0tIDJYbmZKcWhTdVZxQ2RJU1k5RWU4
            K1QxdENqOStjSzZ0K3VoSThOMXNzOFEKVMhTylV0HVdHdRQJKJkWYNqL3FZQmOwC
            VpWBxaFHrVh7z11qAkips0W45ur45zR87IwSs+fcfn/+7O1mfeTsEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:32Z"
    mac: ENC[AES256_GCM,data:KQo7k4b9RfQ42G7xQMIvEeFAHd8t1KXq33zzKAI7YPWBO5OuGgWJnlaANSchCxZji7SOOjbm8q1DsTDce2QDRrw138k24yzH8+247L9A6MmNFzSMF2kdwWMlunk8OOLTs1ZzzhlmJ5tOKyNHqh3JCPj42xD1Cb7R7vBJtMLxeTg=,iv:/x/9CahLLNqgNF5Qp6KG4GSuQMANTHtIE12wntLmBOU=,tag:kLFeCm7OaqTnotT6MbGfXQ==,type:str]
    version: 3.13.3
