apiVersion: v1
kind: Secret
metadata:
    name: lake-s3-iceberg-sink
    namespace: kafka
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:xhzNeAvRCYvjUz9/UTMw/OR9J+w=,iv:iQJElfut9zrm5UoSG19cUzlPDMPZF5q4Yo/lCvWx+3U=,tag:EFImFFZx7Vt968MCOsUxgg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:ZmRFkb8hpZh8gRxTI+UO50kmkf3DW6UpAUuhzT71LWYUW6+/V6NXzQ==,iv:GA+eArA0hMuWSycPJ/qQCkJZ7E3pGZ/5eU0rvpo2q14=,tag:VWJgGOm5T5RlRRg+sLcr+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuOEIwdGJZczNrN09TRGF0
            V3hzVnp3WnlXenk0OE1HQzJ2WlA1WFdGbVVjCnJQQVE1M2VMNzJnSlB1YVJIK0xy
            YmIyTWQ0SHI3OUdaUXJTM09vUHk0SU0KLS0tIDVFbjZJNk9oK1VoMEw0NEFQaFhH
            TVFUNTcxOEtuWFdRcHNBZFNCaFBQUFEKaUtCv2dbfAerudk7RW5K4ADg40XgES12
            wNmPe1h/neArlSmqQezelsAaXpjLhDRHax4uKjBZxxnplbIdlh1/pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:aZ3TNxyIDNwLXpqEUis7syAnWgI2RvkFVjFn4pW7K3+4YMB5voHQ3BS84k9hfi8ik7qLanTve5AARKeUUwKsVzqRz7egz2TMUF+tQw6w390fmA/NA3sC32TRNzOebUSW1q2Wxt8xGTUJ4zId0N4DktIK5PGNUKf+hKrSEF8z2fA=,iv:h3gjVq7Ncw5ZLDbupWtGqBB9n9HCG/fyjymJgBqXXGs=,tag:DdkMB1/QSYyP9/EnhxvpPA==,type:str]
    version: 3.13.3
