apiVersion: v1
kind: Secret
metadata:
    name: polaris-storage
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:fwJc0konB36cZ7zZUYfUJu30yxw=,iv:eFvh6FYrRMBnCZoIz5auxcpmySI48sntY3KDpWerM3U=,tag:RcFHYPMFfMu9ytkCR3mVqg==,type:str]
    secret-access-key: ENC[AES256_GCM,data:s1wRsCTSqkb7eARay98iTeusjDFOCDHWu2Y4qzqeI/QzHH7DYN06nQ==,iv:Zpek86piOmwU09MI5qiCKp66CewraENNEUAVGMW8ETk=,tag:gmz5icNSR5XbhVF1NnIVbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTkh2alVjUW54djM2TjNk
            djNSNlVFeGpDcndkM0NIM0JsNEtrWDZ6Znh3CjBZcHVpNDM5dDZVRVV1YVI0dC9L
            R3pTV0JUam5sL1k1dTFOQVlSaDF5d1UKLS0tIEtxclprQmtZL1piSFlRRXQ2d3dX
            cVZ6OUVQZWxQTFRHV3A4ZjFGQjBjTVEKV+vFJa80BW14TM79C1Y9bvqwNPo902eP
            28uP0MaF2BLKsCDmwE/9ssF3i6Rw94TVBIuQZXUH0KxgroA6XS/x8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:+ou5nTFuueXWAXf0O8dIVDBKcAXcs0dJ+T2xfsoS30lTjNtPpBU21C4dLFn+HjwMeLPDDqO6oQlm/GuBfhdXMv0yUuDNxsfVip2j6BM/Oegi3GJG4hvoI4vCo34QHiGpJxmWTQitfQzrfRr50MgAof4EC+xaSGHc+sd/HdFsd2k=,iv:CKiiVurba/FufokuMT22PF35W/6g1W3/Gy4g9dw9RuI=,tag:Uqyw5t3gxDBvCC+/ZTrDkQ==,type:str]
    version: 3.13.3
