apiVersion: v1
kind: Secret
metadata:
    name: polaris-root
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:X5z/Zg==,iv:b81HTWwZBxU3wnm0wrqtzvMcNnMhl8chXqUNWpVls3U=,tag:YDI+GKQItoKKvbZpFUJYIg==,type:str]
    client-secret: ENC[AES256_GCM,data:ZcoHBTBSQwTQBar/wRfV6d4/f7HUWf/Ct2ghRv3JznVD1fZsMh/jUZa+KJrxgpGj,iv:5+wMKxIIZnw2rCh+Jtb+Nb66A18eMfCHltmNCZkNwnw=,tag:0Co6aHa/hDBSVM3W1yEnWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3dWNJaURXT1AzNWlDZEhD
            OWZzR25oTFFGeDNGSW5MZjhZczVTdTIyS2pVCmY4anpHY095SHNMYVlIbURMdXlV
            VUVwR0pWcyt1WFhTYWM3cjNYbWZmYzAKLS0tIHN5WUNsUGt3UlMyWlFPYm5FWkIv
            Mk9OOEhkaGlMSnVLMGt1SjAraGZVYjAKbrowu9JMXtQuc4t7Z1ecNRQRFAcP+Rut
            zQVQnhgZif9UJrbPWiL7p0+oGCqoQnLLWah/qBe9wtrVOjqsNXy5Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-10T07:43:12Z"
    mac: ENC[AES256_GCM,data:t3djRMSIcLWbS/Azdx4SJUJUi1OhM865WGSZTB1ANfZ76k5tKB0OaooW2O7qf8xZkgWPcguLTJcqp1Ua5Uds0Lvc+oRl1ftpsCaCfJd3KCp8tfe9boPkYe9fg3SF/768CZLFZbKYCRvMdveaeZmruFYh9tAuvAAwaU/lB98SaLU=,iv:zhCY4KurIfVrVsxOOBwI1dbua9cJ1MWucfQZr8VuY2c=,tag:pwnRPPv7tqZ94bd6lmAgPg==,type:str]
    version: 3.13.3
