apiVersion: v1
kind: Secret
metadata:
    name: polaris-root
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:vTYRLA==,iv:OJmFxsB1YQn+adTSctvxWLnrS4KqWa9vf4/Nk2kkZ0o=,tag:H2oKBPyV1iiLOXB9Z0SHMw==,type:str]
    client-secret: ENC[AES256_GCM,data:Y3GARL8po5kGy2n8kwgBHuAyEuwpaXH3h9pK5oiYG7zf3YlUP19f82kOWdH/8a9A,iv:JBjvtQ4XDbx0mJicddSiF9SVUfPZ6NDpn+owSFkQhFM=,tag:xxEgjZePeEEvT7UxZIhTyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWUlIQmRaOFNFbXdkeGs2
            TWM2Z2haNHkwRllPTjFKUEdadjlKTGZkKzI0CmdUV001VE1IUStqSTJWTW02dFBY
            ZUJxTFlwNVUwUjdwdUlIT2RiSERrQlUKLS0tIDRhSkFCWEVLRllqaVl0T0g4dE9Y
            d2JCR051WWNqdkx3Uk1MTUtURjRIQ0UKYK6JtBuVAYPBYvdQusmw4WTwL+E1bomj
            Rp4z/mEdGRPI1kfBN/V+G02An3DSeorcDnNc8ObraNaQraG6B1OdoQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:31Z"
    mac: ENC[AES256_GCM,data:7a5nB1/+dl2ikq4gLg8uEf20jyO8UYHcf/6gbmB7g42SdvNuNJ0C/PXP/8Jf54VRbC5JDi0PT0W/3fpqn0XUrmRfgkcAlmf2obK59dr1ZO3MmQUupbwhlL/oRP+ZMr+hDwGvrZMXkh0x6JPWVnKWPqDt3SYtMzWlRiSNzwg5/wg=,iv:dU6aNbMcrHQASXq5S2Bxri7ue1tv6AXaInAFzIkIxjg=,tag:HrxkS42qcZLHB/oH+elyZw==,type:str]
    version: 3.13.3
