apiVersion: v1
kind: Secret
metadata:
    name: polaris-storage
    namespace: lakehouse
    labels:
        app.kubernetes.io/part-of: shopflow
type: Opaque
stringData:
    access-key-id: ENC[AES256_GCM,data:wo/srzX8BRz43KfjHylWSJ3kUtQ=,iv:o7SMJZwR/4rVGKkjJuqGJM3nmOAaxKiWeNQPQlnkyiM=,tag:vdF0SyKHz/PMHUVSnpiSCQ==,type:str]
    secret-access-key: ENC[AES256_GCM,data:eym/gGXtktEb/QNgAm/fZ/zptzvGVsyZjIAZ0iukaoQ5do3MJ5FTcg==,iv:uOAW7N+UDLWGrk4cbd5Iyu2prqJvbdEt8fK3673IZio=,tag:6lux9d3Hzh0PC2v0ucnoeg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6ME9vdUVtRjByS25nZU4v
            ZWtmbStNRTRwUjM2WFBTTHJFYUkwanM1RWc4Cjd4VDZLR3FETkRFeGxjbEEzN0Mx
            RzB6NnpkWU84Y2lSUVRCVmxFL2hQcFEKLS0tIDZYWTR2WWJKMCs1WGxKNnludzNu
            cUZaVjE2MVJEd1RKYWlzbVBtNUhOT28KkJ9yAAZEHqr6qS2Y6XleTXrwG8MXDMTl
            6PFdwZw0SeU6SWQzKvsXpQmqD9juVAyVsYL8ndQf5LiWzvsVozRwvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a6zmtke62fs5cpa55jczu78at35j4skx97esmxuuzkjcndfxxvdqvemt4q
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T13:07:31Z"
    mac: ENC[AES256_GCM,data:25TbJVCdSOMv5lRpKLmmPDCP0y5/XXvcwj/nqMh/SJRIYHVMGFv9BV5lYKdkPZ4OaSA2TPXDTreHhq8mpb4WUGoXEMvhXp/bci5dGEiAnQfpFOQHTe8Kh1oZE8F8q9ZUCi1RwbMxuYRlDkvZBDKtF3t6OCVqiwED2+kqs7VU+9k=,iv:3EztX45qImcZ2ncqmwhGUQkTrG453ogM0oaCap/Kw8k=,tag:9r79kyeH/CHW3pYedt69DA==,type:str]
    version: 3.13.3
